services:
  - type: web
    name: discord-giveaway-bot
    env: python
    buildCommand: pip install -r pyproject.toml
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
