services:
  - type: web
    name: discord-giveaway-bot
    env: python
    buildCommand: pip install -U pip && pip install discord.py flask flask-sqlalchemy gunicorn python-dotenv sqlalchemy psycopg2-binary
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPORT
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    # Uncomment if you want to add a database
    # plan: free
    # databases:
    #  - name: discord-giveaway-bot-db
    #    plan: free
